# Generated by Django 3.2.3 on 2021-06-22 00:16

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('idComponente', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del componente')),
                ('nombreComponente', models.CharField(max_length=99, verbose_name='Nombre del Componente')),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('idFabricante', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Fabricante ')),
                ('nombreFabricante', models.CharField(max_length=99, verbose_name='Nombre del Fabricate ')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Producto ')),
                ('nombreProducto', models.CharField(max_length=99, verbose_name='Nombre del Producto ')),
                ('precio', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=core.models.Producto.ruta_imagen)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.componente')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fabricante')),
            ],
        ),
    ]
